global:
  scrape_interval: 15s # How often to scrape targets by default

scrape_configs:
  - job_name: "fastapi_app" # A name to identify this scrape job
    scrape_interval: 5s # Override the global default for this job
    static_configs:
      - targets: ["localhost:9464"] # The address of your FastAPI app's Prometheus metrics
